### ISSUE TITLE
Feature Request: Cleanup key in post

### ISSUE THREAD

**Issue by jsg2021** [shimataro/ssh-key-action#145]
It would be nice to delete the `.ssh` directory in the post process life cycle: 
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions

example:

```yml
runs:
  using: "node12"
  main: "lib/main.js"
  post: "lib/cleanup.js"
```
