### ISSUE TITLE
 EEXIST: file already exists, open 'C:\Windows\ServiceProfiles\NetworkService\.ssh\id_rsa

### ISSUE THREAD

**Issue by jmdollosa** [shimataro/ssh-key-action#160]
Works great! However on the second attempt to run my workflow I get this error

`EEXIST: file already exists, open 'C:\Windows\ServiceProfiles\NetworkService\.ssh\id_rsa`

Are there any work arounds for this issue?

Thanks!

**Comment by lucasdemarchi** [comment]
Not ideal, but I "fixed" this by just adding a step to remove the file

**Comment by chenghuang-mdsol** [comment]
yep. there should be something to make ssh agent to use a precleaned temp folder.

**Comment by shimataro** [comment]
Very sorry for late response.

Could you show me reproducible repository, especially YAML file for GitHub Actions?

**Comment by dcfsc** [comment]
We are using self-hosted GitHub Action runners and they do not start from a brand new runner each time. Files left in the home directory persist. Ours are Linux, but the same issue.

```
    steps:
      - name: Setup Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ID_GITHUB_ACTIONS_MACHINE_USER_RSA }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.SSH_KNOWN_HOST }}
```
The first run creates the `~/.ssh/id_rsa` file with the valid private key.

The second run fails as mentioned:
```
Run shimataro/ssh-key-action@v2
  with:
    key: ***
    name: id_rsa
    known_hosts: ***
Error: EEXIST: file already exists, open '/home/admin/.ssh/id_rsa'
```
an option might allow ignoring this situation and completing the build:

```
- name: Install SSH key
  uses: shimataro/ssh-key-action@v2
  with:
    key: ${{ secrets.ID_GITHUB_ACTIONS_MACHINE_USER_RSA }}
    name: id_rsa # optional
    known_hosts: ${{ secrets.SSH_KNOWN_HOST }}
    if_exists: replace < if file exists, replace the existing key>
 OR 
    if_exists: ignore <if file exists, do not replace >
DEFAULT
    if_exists: fail  < if file exists, fail>

```
This would allow us to create a key when on a new self-hosted runner, but continue when the key has already been created. 

In either case, the Action would then just install the key into `ssh-agent` as now.

**Comment by shimataro** [comment]
@dcfsc 
> Files left in the home directory persist.

Thank you for the information, It must be a cause!

```yaml
- name: Install SSH key
  uses: shimataro/ssh-key-action@v2
  with:
    key: ${{ secrets.ID_GITHUB_ACTIONS_MACHINE_USER_RSA }}
    name: id_rsa # optional
    known_hosts: ${{ secrets.SSH_KNOWN_HOST }}
    if_exists: replace < if file exists, replace the existing key>
 OR 
    if_exists: ignore <if file exists, do not replace >
DEFAULT
    if_exists: fail  < if file exists, fail>
```

It's a good idea! Thank you again!

**Comment by shimataro** [comment]
Hi,
I added `if_key_exists` parameter on `feature/if_key_exists` branch.

You can test it by using `shimataro/ssh-key-action@feature/if_key_exists`.

```yaml
runs-on: ubuntu-latest
steps:
- name: Install SSH key
  uses: shimataro/ssh-key-action@feature/if_key_exists
  with:
    key: ${{ secrets.SSH_KEY }}
    known_hosts: ${{ secrets.KNOWN_HOSTS }}
    if_key_exists: replace # replace / ignore / fail; optional (defaults to fail)
```
