### ISSUE TITLE
Feature Request: Allow multiple keys to be setup for a single remote host

### ISSUE THREAD

**Issue by MiltiadisKoutsokeras** [shimataro/ssh-key-action#200]
Hi and thank you for your useful tool,

I have stumbled on a setup that maybe cannot be covered by your tool or any similar. GitHub does not allow to have a single SSH Deploy Key for all your projects, you are forced to create a pair per project. If you want now to use 2 projects on a GitHub Action, it is not possible to define more than one key on the same host (github.com in our case) like this:

```yaml
name: Multiple SSH keys in one host
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-bullseye
    steps:
      - name: NodeJS installation
        shell: bash
        run: apt update && apt install --assume-yes nodejs
      - name: GitHub SSH Authentication for Project 1
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY_PROJECT_1}}
          name: project_1
          # Required once per host
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: GitHub SSH Authentication for Project 2
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY_PROJECT_2 }}
          name: project_2
      - name: Prepare the Python environment
        shell: bash
        run: bash ${GITHUB_WORKSPACE}/.github/scripts/create_python_venv.sh
```

where in `.github/scripts/create_python_venv.sh` there is `pip install -r requirements.txt` command which contains the following:

```
# requirements.txt
git+ssh://git@github.com/myuser/project_1.git@develop#egg=project_1
git+ssh://git@github.com/myuser/project_2.git@develop#egg=project_2
```

As both URLs in requirements file require a different SSH key pair to work even though the host is the same.
