### ISSUE TITLE
"known_hosts" option

### ISSUE THREAD

**Issue by shimataro** [shimataro/ssh-key-action#24]
`StrictHostKeyChecking=no` option is not secure.
`.ssh/known_hosts` is required for security.

example:

```yaml
- name: Install SSH key
  uses: shimataro/ssh-key-action@v1
  with:
    private-key: ${{ secrets.SSH_KEY }}
    public-key: ${{ secrets.SSH_KEY_PUBLIC }}
    name: id_rsa # optional
    known-hosts: ${{ secrets.KNOWN_HOSTS }} # optional
```
