### ISSUE TITLE
Permission denied (publickey,gssapi-keyex,gssapi-with-mic)

### ISSUE THREAD

**Issue by falstack** [shimataro/ssh-key-action#85]
``` yml
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v1
        with:
          name: id_rsa-prod
          private-key: ${{ secrets.RSA_KEY }}
          known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          config: |
            Host prod
              HostName ${{ secrets.SERVER_IP }}
              Port ${{ secrets.SERVER_PORT }}
              User ${{ secrets.SERVER_USER }}

      - name: Publish
        run: |
          ssh prod -tt -i ~/.ssh/id_rsa-prod
```
output
``` shell
Run ssh prod -tt -i ~/.ssh/id_rsa-prod
***@***: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
##[error]Process completed with exit code 255.
```

my sshd_config
```
PasswordAuthentication no
RSAAuthentication yes
PubkeyAuthentication yes
```

How can i do?
